load('ext://darwin_patch', 'darwin_patch')

def lxc_extension(name='', command='', deps=[], ignore=[], kustomize_path=''):
  custom_build(name, command, deps, ignore=ignore)
  k8s_yaml(darwin_patch(kustomize(kustomize_path)))